# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0002_auto_20170410_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='ip_address',
            field=models.CharField(default='ABC', max_length=120),
        ),
    ]
