# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0006_auto_20170411_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='ref_id',
            field=models.CharField(default='ABC', max_length=120, unique=True),
        ),
    ]
